version: "3.9"

services:
  client:
    image: vineeshw1994/swarm-blog-client:latest
    ports:
      - "3001:80"
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
